site_name: Scimon
repo_url: https://github.com/Gausix/Scimon
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - content.tabs.link
    - content.footnote.tooltips
  
  palette:
    - media: "(prefers-color-scheme: light"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - How to build: build.md
  - Basic usage: basic-usage.md
  - Commands: commands.md
  - Scrape: scrape.md
  - Providers: providers.md
  - LaTeX Compiler: compile.md
  - Syntax:
    - Overview: syntax/what-is.md
    - Comments: syntax/comments.md
    - Metadata: syntax/metadata.md
    - Downloads Block: syntax/download-block.md
    - Readme Block: syntax/readme-block.md
    - Commands Block: syntax/commands-block.md
    - AI Block: syntax/ai-block.md
    - Compress folder: syntax/compress.md
    - Copy folder: syntax/copy.md
    - Open links: syntax/open-links.md
    - Style: syntax/style.md
    - Print: syntax/prints.md
    - Covers: syntax/covers.md
    - QR Code: syntax/qrcode.md
    - Math: syntax/math.md
    - Server: syntax/server.md
  - Markdown: syntax/markdown-render.md
  - Configs:
    - Scimon.yml file: configs/scimon.yml-file.md
    - .env file: configs/env-file.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra:
    social:
      - icon: fontawesome/solid/blog
        link: https://kremilly.com
        name: Blog
        
      - icon: fontawesome/brands/x-twitter
        link: https://x.com/import_kremilly
        name: Twitter
    
    generator: false

copyright: Copyright &copy; 2025 Gausix